### PR TITLE
tests(e2e): server with client queries

### LINKED ISSUE #28: nexus-prisma e2e test
e2e test:

- setup project
- try build
- launch server try queries

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes #28

### CODE REVIEW

**Comment by bweis** [comment]
@jasonkuhrt In 4bfcc76 you left an exposed Heroku DB string with user and password inline.  You might want to regenerate the DB and store those in environment variables.  Otherwise people can maliciously cause tests to fail.

**Comment by jasonkuhrt** [comment]
> Otherwise people can maliciously cause tests to fail.

That's true but not a major concern right now

**Comment by jasonkuhrt** [comment]
Going to merge as it is only failing in Windows now.

**Pull request merged**
