### PR TITLE
deps: upgrade to latest prisma & fix tests

### LINKED ISSUE #78: Fix tests
#### What

- tests on trunk are broken

#### Why

- since 2704ff2c0954cf591136bc7fbce6d6cd189f56c9

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes #78

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
@janpio @Jolg42 It used to be that this worked. The prisma client was specified to be output at `./client` or something. After a Prisma upgrade https://github.com/prisma/nexus-prisma/commit/2704ff2c0954cf591136bc7fbce6d6cd189f56c9 to `2.24` tests began to break.

```ts
  execa.commandSync(`yarn -s prisma db push --force-reset --schema ${dir}/schema.prisma`)
```

I fixed this once using Jest `runInBand`. The commit above. That tells me that two Jest test suites were conflicting. And indeed the test error output indicates snapshots failing with results from one another.

Having to use `runInBand` is a hack, not ideal etc. It is also not a big deal. The worst of it is using it when not knowing _why_, as is the case now.

I am going to try to change `execa` (shown above) to run so that it is actually spawning the child process IN the dir, rather than given a path to the schema in the dir. I am betting that will get things working again, how they used to, without `runInBand`.

**Comment by jasonkuhrt** [comment]
@Jolg42 maybe the issue was how prisma schema output relative paths were resolved? I have been doing `output = './client'` so far.

**Comment by jasonkuhrt** [comment]
My solution worked I think, but the relative path stuff isn't working on Windows. https://github.com/prisma/nexus-prisma/pull/85/checks?check_run_id=2879192617 I thought it might not.

**Comment by jasonkuhrt** [comment]
@Jolg42 Is it expected that absolute Windows paths are not supported? https://github.com/prisma/nexus-prisma/runs/2879275828#step:9:632 Note that this might not be a valid Windows path because of the later `/`...

**Comment by jasonkuhrt** [comment]
I have no idea what is going on, the macos tests pass on everything but then hang on trying to run the next integration test.

When I run in band, there is no issue.

On my machine, there is no issue.

:( 

Well, I did my best, here comes `runInBand` at least for now.

**Comment by Jolg42** [comment]
Might be related to @millsp PR I think

**Pull request merged**
